apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: ganeshbabupasala/book-catalog:latest  
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part2_a7pq_user:CTdmjKwCYEEEakg5scv0qQRsiVd2lI1o@dpg-creok7ogph6c73eu4ls0-a.oregon-postgres.render.com/sit722_part2_a7pq"  # Use your Render DB URL
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001  
  selector:
    app: book-catalog
